### ISSUE TITLE
Menu border for Windows on Exaile 4

### ISSUE THREAD

**Issue by dangmai** [exaile/exaile#196]
On Windows 8, the context menu doesn't have border, making it quite hard to tell it apart from the background at a glance - here are some screenshots:
https://i.imgur.com/qqnxrbp.png
https://i.imgur.com/J08OKt2.png
As far as I know this is not an issue with Exaile 3.x.

**Comment by genodeftest** [comment]
This looks like an issue with your Gtk+ 3.x theme. Probably an issue in Gtk+ on Windows.
Are you using any specific Gtk+ 3.x theme?

**Comment by dangmai** [comment]
I just reinstalled my Windows VM so I doubt that I have a specific Gtk theme there

**Comment by genodeftest** [comment]
When you are running exaile, can you please tell me the Gtk+ version bundled in your exaile build? It should be printed to cli (you might have to add the `--debug` switch) or in your logfile in `%USERPROFILE%\AppData\Local\exaile\logs`.

**Comment by dangmai** [comment]
Here's the log for a brief run of Exaile:

```
01:25:29 INFO    : Using PyGObject 3.14.0 (xl.main)
01:25:29 INFO    : Loading Exaile 4.0.0dev on Python 2.7.10... (xl.main)
01:25:29 INFO    : Loading settings... (xl.main)
01:25:29 INFO    : Using English_United States 1252 locale (xl.main)
01:25:29 INFO    : Using GTK+ 3.14.15 (xlgui)
01:25:29 INFO    : Using GStreamer 1.4.5 (xl.player.gst)
01:25:29 INFO    : Reconfiguring crossfading (xl.player.gst.engine [player])
01:25:29 INFO    : Crossfade: disabled (xl.player.gst.engine [player])
01:25:29 INFO    : Loading plugins... (xl.main)
01:25:29 INFO    : Loading collection... (xl.main)
01:25:32 INFO    : Loading devices... (xl.main)
01:25:32 INFO    : Loading interface... (xl.main)
01:25:33 INFO    : Loading main window... (xlgui)
01:25:33 INFO    : Connecting main window events... (xlgui.main)
01:25:33 INFO    : Loading panels... (xlgui.panels)
01:25:33 INFO    : Connecting panel events... (xlgui)
01:25:33 INFO    : Done loading main window... (xlgui)
01:25:33 INFO    : Reconfiguring crossfading (xl.player.gst.engine [preview_device])
01:25:33 INFO    : Crossfade: disabled (xl.player.gst.engine [preview_device])
01:25:39 INFO    : Exaile is shutting down... (xl.main)
01:25:39 INFO    : Disabling plugins... (xl.main)
01:25:39 INFO    : Saving state... (xl.main)
01:25:39 INFO    : Bye! (xl.main)
```

I think I'm just running the Gtk+ that's included in the AIO in the Exaile installer.

**Comment by genodeftest** [comment]
Hm, I'm wondering why it ships 3.14.15 and not 3.16.x or 3.18.x. Maybe that's the latest stable release for Windows. Anyway I'm reporting an issue in Gtk+ since now I am quite sure that this issue is not exailes fault.
https://bugzilla.gnome.org/show_bug.cgi?id=759449

**Comment by sjohannes** [comment]
I think this is fixed in later versions of GTK+. I used to have the same issue in GTK+ 3.14 but not in 3.18 (there's a grey border now).

**Comment by dangmai** [comment]
Neat! I knew Dustin was uploading 3.18 to his mirror last night, so I'll reinstall it once he does to check if the issue has been resolved.

**Comment by dangmai** [comment]
I'm on Windows 7 now and just test run Exaile with GTK 3.18.2 and the problem is still there.

**Comment by virtuald** [comment]
@dangmai I think you were running with the pyinstaller bundled version of Exaile, correct? It's possible that a data file was omitted for this. Would need to test with the non-bundled version to make sure.

**Comment by dangmai** [comment]
I ran Exaile on Window 8 from the Exaile installer, but on Windows 7 I just run it straight off the source code (with the 3.18 GTK AIO installed)

**Comment by virtuald** [comment]
This sounds like an upstream bug then, not sure what we can do about it here. Might be a bug in a specific version of GTK AIO?

**Comment by lazka** [comment]
I use the following: https://github.com/quodlibet/quodlibet/blob/master/quodlibet/quodlibet/__init__.py#L333

**Comment by dangmai** [comment]
I no longer run into this issue using the GTK version included with MSYS2. [Proof](http://imgur.com/a/m5Yo3)
